version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_hangthailan
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: php/Dockerfile-php
    container_name: php_hangthailan
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_hangthailan
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_hangthailan
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: your_root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql