# Use the official PHP php:8.2-fpm image
FROM php:8.2-fpm

# Set the timezone
ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install additional packages and extensions
RUN apt-get update && apt-get install -y libzip-dev unzip
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip
RUN apt-get install -y nodejs npm

# Install MySQLi extension
RUN docker-php-ext-install pdo_mysql mysqli zip

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory contents
COPY . /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set permissions
RUN chown -R www-data:www-data /var/www/html

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
